### ISSUE TITLE
第六章：6.1.6，翻译错误

### ISSUE THREAD

**Issue by yinmazuo** [docschina/ecma262-old#56]
原文的意思应该是“ m是小于2的52次方的正整数”，翻译的是“m是小于52的正整数”，如下图。

![image](https://user-images.githubusercontent.com/9531951/45274840-c1690680-b4eb-11e8-9f1e-2e4de3c67a40.png)

![image](https://user-images.githubusercontent.com/9531951/45274860-cd54c880-b4eb-11e8-862f-6ea3ff1a10dd.png)

**Comment by realywithoutname** [comment]
可以 PR 哦，新工作后，都没时间来做这个了

**Comment by realywithoutname** [comment]
已修改
